### ISSUE TITLE
My Tutorials (Completed): Giant completed checkmark

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#493] opened 2020-09-29 06:53 UTC
On the My Tutorials (Completed) tab there often appears a giant checkmark

![IMG_5186](https://user-images.githubusercontent.com/5320361/94523260-36bde600-0231-11eb-9a15-07919043917c.jpg)

### Steps to reproduce

Navigate to the My Tutorials (Completed) Tab

### Expected behavior

Completed badge should look normal

### Actual behavior

Completed badge checkmark is huge

### Environment

* iOS Version: iOS 14
* raywenderlich.com App Version: 1.0.4
* Device: iPhone 11

**Comment by bladebunny** [comment] 2020-10-07 17:03
I've taken a quick look at this.  It looks as though TagView was intended to be able to respond to Size preference changes.  I don't see where (very new to this code) there's a capability to change this currently.  

Even though the callback never sees a different 'height' for an icon, if present, in TagView than 12, it seems like a bug in Image that the dynamic binding is resulting in the observed layout issues - perhaps because a container view is having trouble calculating its size?  

I would suggest a quick fix of just locking the image height in TagView to 12 pts to resolve this for the time time-being.  

I can submit  a PR with with this change if you like - I've verified it fixes the presenting issue.  Resolving this for dynamic TagView size changes would have to be looked at again later.

**Closed as completed** 2020-11-11 11:13 UTC
Labels: bug, ui-bug, good first issue
